import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Header/Navigation";
import Footer from "@/components/footer/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Find website",
  description: "Generated by create by thang and tri",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-seri px-2 flex flex-col min-h-screen">
      <div className="flex-grow">

        <Navigation>

        </Navigation>
        
        {children}


        </div>
        <Footer></Footer>
        </body>

    </html>
  );
}
